// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFq7N4XrcD3sZE0b9vVq7y2d04uBnA8U',
    appId: '1:81017860320:web:4ac4720d3e7da5ecdf6085',
    messagingSenderId: '81017860320',
    projectId: 'ce-mas',
    authDomain: 'ce-mas.firebaseapp.com',
    storageBucket: 'ce-mas.firebasestorage.app',
    measurementId: 'G-Q99EPR25SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-S_lj4b7_lx8-lgvzOUTtOLMeGe1pqVo',
    appId: '1:81017860320:android:aef8bd4afe28f0f6df6085',
    messagingSenderId: '81017860320',
    projectId: 'ce-mas',
    storageBucket: 'ce-mas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOl8Cpw3EWJn3vtUddxCBRR7SnqObQpmQ',
    appId: '1:81017860320:ios:e2022ddf073a9cd0df6085',
    messagingSenderId: '81017860320',
    projectId: 'ce-mas',
    storageBucket: 'ce-mas.firebasestorage.app',
    iosClientId: '81017860320-gq7ngkc9kkm5tf0kr52bt6ft4du18ppv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cemas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOl8Cpw3EWJn3vtUddxCBRR7SnqObQpmQ',
    appId: '1:81017860320:ios:e2022ddf073a9cd0df6085',
    messagingSenderId: '81017860320',
    projectId: 'ce-mas',
    storageBucket: 'ce-mas.firebasestorage.app',
    iosClientId: '81017860320-gq7ngkc9kkm5tf0kr52bt6ft4du18ppv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cemas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNFq7N4XrcD3sZE0b9vVq7y2d04uBnA8U',
    appId: '1:81017860320:web:0cb02e484fad8fa5df6085',
    messagingSenderId: '81017860320',
    projectId: 'ce-mas',
    authDomain: 'ce-mas.firebaseapp.com',
    storageBucket: 'ce-mas.firebasestorage.app',
    measurementId: 'G-QW8EVBRF51',
  );

}